sudo: required
language: bash
services:
  - docker
before_install:
  - docker pull lacti/jekyll-aws
script:
  - |
    docker \
      run -it \
        -e AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} \
        -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
        -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
        -v ${PWD}:/opt \
      lacti/jekyll-aws \
      /bin/bash -c "cd /opt; /bin/bash /opt/sync.sh"
notifications:
  slack:
    secure: mnz4ouzXXpBb0VNX2y4ZWSVouNXRadhbi936xX4ywVaIykiHjtGgKClZnG7Jj3lGy8orcY99g2Dods8NZsM2LCIBABfVLCFPObgxkvAEfbNPDL8rEhgUmgs6/gcn15pNY94nmranWojv5QUMQBjIHv3tZ4kLNQPDrOZfSM2x7g4Fz+R4j/1ffTW6uSoxkrg16swOGSm7xY+WrROFfb3NuT7YOV7ezu3tXG2ATOBEQzu2lfx/Hlz6lNmJ8gulbpYHb5EYYF41nKBhXlg974BVEo/RjABDtf1ZxlI0CZmkEOsQTh0XJLahwp5bsFNmOrtq5tjdQ46Zi1U0qvkvCzohwQ4Wj7DnMOGdJIFT3sYqT0ohtDvPinSx6h4Ei0SW/usAifQmfno4SmKorqD1hWhM/OvnYdx/cryES3F3imWrW/be4n/kY42ttM+xLBTjFjSOHq3wviUBI9MXYKPdCk5gEZmoivZML+8kAgOQp7unjYBK2nBsudWSU1NhAqSvLfKAFxq/uyYFW/H9sZ8uCc2S4n/Q4qg2B1ce/iojducSo4p7G/Csv2Rey9fHzsyuXqUI7f3JBgiIBsts3CcXX+CoN/fJTpHFOtjG2YGfWM/E5KhogbP0GcLmf62MH8JE7NIZjEbuvH32bcuIbOOcCsIU+OVeV6Vf1NzvA7THBNAC92g=
